#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 07 16:59:21 MDT 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_riscv_pipeline_behav -key {Behavioral:sim_1:Functional:tb_riscv_pipeline} -tclbatch tb_riscv_pipeline.tcl -view /home/ethan/Documents/ECE485/stage4/ece485_final_cadet_stage4/tb_riscv_pipeline_behav.wcfg -log simulate.log"
xsim tb_riscv_pipeline_behav -key {Behavioral:sim_1:Functional:tb_riscv_pipeline} -tclbatch tb_riscv_pipeline.tcl -view /home/ethan/Documents/ECE485/stage4/ece485_final_cadet_stage4/tb_riscv_pipeline_behav.wcfg -log simulate.log

